version: "3.8"

services:
  next:
    image: next
    build:
      context: frontend
    container_name: next
    restart: unless-stopped
    ports:
      - 3000:3000

  strapi:
    image: strapi
    build:
      context: backend
    container_name: strapi
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ~/strapi-uploads:/opt/app/public/uploads
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - ~/strapi-db-data-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl/new.ararat.chessnews.am
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/nginx/conf.d/ssl-dhparams.pem
    depends_on:
      - next
      - strapi

#   phpmyadmin:
#     image: phpmyadmin
#     restart: always
#     ports:
#       - 8080:80
#     environment:
#       PMA_HOST: strapiDB
#       PMA_PORT: 3306
#     depends_on:
#       - strapiDB

#   elasticsearch: 
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
#     environment:
#       - discovery.type=single-node
#       -  xpack.security.enabled=false
#       #  - ELASTIC_PASSWORD=mys3cur3P@SSw0rd
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     volumes:
#       - ~/es-data:/usr/share/elasticsearch/data
#     container_name: elasticsearch
#     healthcheck:
#       test: curl localhost:9200/_cluster/health?pretty | grep status | grep green
#       interval: 5s
#       timeout: 3s
#       retries: 50




# volumes:
#   es-data:
#     driver: local