version: "3.8"

services:
  next:
    image: next
    build:
      context: frontend
    container_name: araratchessnews-next
    restart: unless-stopped
    ports:
        - 3001:3000
    depends_on:
        - strapi
   
  strapi:
    image: strapi
    build:
      context: backend
    container_name: araratchessnews-strapi
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
        - 1337:1337
    volumes:
      - ./strapi-uploads:/opt/app/public/uploads
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb
    container_name: araratchessnews-mariadb
    restart: unless-stopped
    volumes:
      - ./strapi-db-data-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      
