version: "3.8"

services:
  next:
    image: next
    build:
      context: frontend
    container_name: next
    restart: unless-stopped
   
  strapi:
    image: strapi
    build:
      context: backend
    container_name: strapi
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ~/strapi-uploads:/opt/app/public/uploads
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ~/strapi-db-data-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl/ararat.chessnews.am
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/nginx/conf.d/ssl-dhparams.pem
    depends_on:
      - next
      - strapi
