version: "3.8"

services:
  strapiDb:
    image: mariadb
    environment:
      # TODO: fix env variables to read from env file
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - 3306:3306

  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: strapiDb
      PMA_PORT: 3306
    depends_on:
      - strapiDb