import type { Metadata } from "next";
import Header from "../src/components/header/Header";
import "../styles/variables.css";
import "../styles/global.css";
import "./layout.css";
import LeftMenu from "../src/components/leftMenu/LeftMenu";
import Image from "next/image";
import Links from "../src/components/Links/Links";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main_container">
          <section className="left_menu_container">
            <LeftMenu />
          </section>
          <section className="content_container">{children}</section>
          <section className="links_container">
            <Links />
          </section>
        </main>
      </body>
    </html>
  );
}
